---
title: "cov"
output: html_document
---

### **Component: Covariate Data**

**ORIENTATION**

This component loads the covariate data - that is the data that you wish to use to predict the response data from. Covariate data is in the form of *rasters* containing pixels of various sizes. You must use at least one module before proceeding to the next component. If you are running the app locally, some modules require authentication and instructions of how to gain this can be found in the module guidance. Depending on the size of your response data, some of the covariates may take a considerable time to download.

#### <span class="module_choice">Accessibility</span>
The time required to travel to cities, time required to travel to healthcare using motorized transport and time required to travel to healthcare by walking. Provided by the Malaria Atlas Project via `{malariaAtlas}`. 

#### <span class="module_choice">Climate</span>
Various bioclimatic variables relating to temperature and precipitation. Provided by Worldclim via `{geodata}`.

#### <span class="module_choice">Land use</span>
The percentage of land covered by different classes of land use. Provided by the Copernicus programme.

#### <span class="module_choice">Nighttime lights</span>
Satellite imagery of the intensity of nighttime lights. Provided by NASA via `{blackmarbler}` developed by the World Bank.

#### <span class="module_choice">Distance to water</span>
The distance to surface water. Provided by ESRI using data from USGS and ESA.

#### <span class="module_choice">Population density</span>
Human population density, provided by Worldpop.

#### <span class="module_choice">Upload</span>
Upload your own covariates in the `.tif` format.
