---
title: "Shinyscholar report"
output:
  html_document:
    toc: false
---
# {.tabset .tabset-pills}
```{r results="asis", echo = FALSE, eval = ("resp" %in% gsub("_(.*)", "", names(common$meta)))}
  cat("## Response Data")
```

```{r results="asis", echo = FALSE, eval = ("resp_shape" %in% names(common$meta))}
  cat("### Upload response shapefile")
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("resp_shape" %in% names(common$meta))}
response <- common$shape[[common$response_name]]
plot_response(response)
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("resp_shape" %in% names(common$meta))}
common$shape |> sf::st_drop_geometry()
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("resp_shape" %in% names(common$meta))}
    map <- leaflet() %>%
      addProviderTiles("Esri.WorldTopoMap") 
  shape_map(map, common)
```

```{r results="asis", echo = FALSE, eval = ("resp_combine" %in% names(common$meta))}
  cat("### Combine data from spreadsheet and shapefile")
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("resp_combine" %in% names(common$meta))}
response <- common$shape[[common$response_name]]
plot_response(response)
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("resp_combine" %in% names(common$meta))}
common$shape |> sf::st_drop_geometry()
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("resp_combine" %in% names(common$meta))}
    map <- leaflet() %>%
      addProviderTiles("Esri.WorldTopoMap") 
  shape_map(map, common)
```

```{r results="asis", echo = FALSE, eval = ("resp_download" %in% names(common$meta))}
  cat("### Upload spreadsheet and download boundaries")
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("resp_download" %in% names(common$meta))}
response <- common$shape[[common$response_name]]
plot_response(response)
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("resp_download" %in% names(common$meta))}
common$shape |> sf::st_drop_geometry()
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("resp_download" %in% names(common$meta))}
    map <- leaflet() %>%
      addProviderTiles("Esri.WorldTopoMap") 
  shape_map(map, common)
```

```{r results="asis", echo = FALSE, eval = ("resp_example" %in% names(common$meta))}
  cat("### Load example datasets")
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("resp_example" %in% names(common$meta))}
response <- common$shape[[common$response_name]]
plot_response(response)
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("resp_example" %in% names(common$meta))}
common$shape |> sf::st_drop_geometry()
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("resp_example" %in% names(common$meta))}
    map <- leaflet() %>%
      addProviderTiles("Esri.WorldTopoMap") 
  shape_map(map, common)
```

```{r results="asis", echo = FALSE, eval = ("resp_edit" %in% names(common$meta))}
  cat("### Edit response data")
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("resp_edit" %in% names(common$meta))}
    map <- leaflet() %>%
      addProviderTiles("Esri.WorldTopoMap") 
  map |>
    removeControl("Response") |>
    removeDrawToolbar(clearFeatures = TRUE)
  shape_map(map, common)
  map |>
    addDrawToolbar(polylineOptions = FALSE, circleOptions = FALSE, rectangleOptions = TRUE,
                   markerOptions = FALSE, circleMarkerOptions = FALSE, singleFeature = TRUE,
                   editOptions = editToolbarOptions(edit = TRUE, remove = TRUE))
```

```{r results="asis", echo = FALSE, eval = ("resp_simplify" %in% names(common$meta))}
  cat("### Simplify shapefile geometry")
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("resp_simplify" %in% names(common$meta))}
    map <- leaflet() %>%
      addProviderTiles("Esri.WorldTopoMap") 
  shape_map(map, common)
```

```{r results="asis", echo = FALSE, eval = ("cov" %in% gsub("_(.*)", "", names(common$meta)))}
  cat("## Covariate Data")
```

```{r results="asis", echo = FALSE, eval = ("cov_access" %in% names(common$meta))}
  cat("### Download accessibility to city data from Malaria Atlas")
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("cov_access" %in% names(common$meta))}
    map <- leaflet() %>%
      addProviderTiles("Esri.WorldTopoMap") 
  layer <- common$meta$cov_access$layer
  raster_map(map, common, common$covs[[layer]], layer)
```

```{r results="asis", echo = FALSE, eval = ("cov_bioclim" %in% names(common$meta))}
  cat("### Download climatic data from bioclim")
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("cov_bioclim" %in% names(common$meta))}
    map <- leaflet() %>%
      addProviderTiles("Esri.WorldTopoMap") 
  for (variable in common$meta$cov_bioclim$variables){
    raster_map(map, common, common$covs[[variable]], variable)
  }
```

```{r results="asis", echo = FALSE, eval = ("cov_landuse" %in% names(common$meta))}
  cat("### Download land use data")
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("cov_landuse" %in% names(common$meta))}
    map <- leaflet() %>%
      addProviderTiles("Esri.WorldTopoMap") 
  for (use in common$meta$cov_landuse$uses){
    land_use <- paste0(use, " land use")
    raster_map(map, common, common$covs[[land_use]], land_use)
  }
```

```{r results="asis", echo = FALSE, eval = ("cov_nightlight" %in% names(common$meta))}
  cat("### Download nighttime light raster")
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("cov_nightlight" %in% names(common$meta))}
    map <- leaflet() %>%
      addProviderTiles("Esri.WorldTopoMap") 
  raster_map(map, common, common$covs[["Nighttime light"]], "Nighttime light", common$meta$cov_nightlight$log)
```

```{r results="asis", echo = FALSE, eval = ("cov_water" %in% names(common$meta))}
  cat("### Download distance to surface water raster")
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("cov_water" %in% names(common$meta))}
    map <- leaflet() %>%
      addProviderTiles("Esri.WorldTopoMap") 
  raster_map(map, common, common$covs[["Distance to water"]], "Distance to water")
```

```{r results="asis", echo = FALSE, eval = ("cov_worldpop" %in% names(common$meta))}
  cat("### Download population density from Worldpop")
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("cov_worldpop" %in% names(common$meta))}
    map <- leaflet() %>%
      addProviderTiles("Esri.WorldTopoMap") 
  raster_map(map, common, common$covs[["Population density"]], "Population density", common$meta$cov_worldpop$log)
```

```{r results="asis", echo = FALSE, eval = ("cov_upload" %in% names(common$meta))}
  cat("### Upload covariate rasters")
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("cov_upload" %in% names(common$meta))}
    map <- leaflet() %>%
      addProviderTiles("Esri.WorldTopoMap") 
  for (variable in common$meta$cov_upload$path){
    raster_map(map, common, common$covs[[variable]], variable)
  }
```

```{r results="asis", echo = FALSE, eval = ("agg" %in% gsub("_(.*)", "", names(common$meta)))}
  cat("## Aggregation data")
```

```{r results="asis", echo = FALSE, eval = ("agg_worldpop" %in% names(common$meta))}
  cat("### Download population counts from Worldpop")
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("agg_worldpop" %in% names(common$meta))}
    map <- leaflet() %>%
      addProviderTiles("Esri.WorldTopoMap") 
  raster_map(map, common, common$agg, "Population", common$meta$agg_worldpop$log)
```

```{r results="asis", echo = FALSE, eval = ("agg_landuse" %in% names(common$meta))}
  cat("### Download land use data")
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("agg_landuse" %in% names(common$meta))}
    map <- leaflet() %>%
      addProviderTiles("Esri.WorldTopoMap") 
  raster_map(map, common, common$agg, names(common$agg))
```

```{r results="asis", echo = FALSE, eval = ("agg_upload" %in% names(common$meta))}
  cat("### Upload aggregation raster")
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("agg_upload" %in% names(common$meta))}
    map <- leaflet() %>%
      addProviderTiles("Esri.WorldTopoMap") 
  raster_map(map, common, common$agg, common$meta$agg_upload$name, common$meta$agg_upload$log)
```

```{r results="asis", echo = FALSE, eval = ("agg_uniform" %in% names(common$meta))}
  cat("### Create a uniform aggregation raster")
```

```{r results="asis", echo = FALSE, eval = ("fit" %in% gsub("_(.*)", "", names(common$meta)))}
  cat("## Fit Model")
```

```{r results="asis", echo = FALSE, eval = ("fit_fit" %in% names(common$meta))}
  cat("### Fit disaggregation model")
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("fit_fit" %in% names(common$meta))}

posteriors <- common$fit_plot$posteriors

unique_types <- unique(posteriors$type)

plots <- lapply(unique_types, function(type) {
subset_data <- posteriors[posteriors$type == type, ]

plotly::plot_ly(subset_data,
y = ~parameter,
x = ~mean,
type = "scatter",
mode = "markers",
marker = list(color = "black"),
error_x = list(array = ~sd, color = "blue")) |>
plotly::layout(title = list(text = type, x = 0.5),
xaxis = list(title = "SD", showline = TRUE, zeroline = FALSE),
yaxis = list(title = "Parameter", showline = TRUE, zeroline = FALSE,
range = c(-1, nrow(subset_data))),
margin = list(t = 100))
})

# Combine subplots into a single plot
final_plot <- plotly::subplot(plots, nrows = 1, shareX = FALSE, margin = 0.05) |>
plotly::layout(title = "Model parameters (excluding random effects)",
showlegend = FALSE)

final_plot

```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("fit_fit" %in% names(common$meta))}
data <- common$fit_plot$data
title <- common$fit_plot$title

x_range <- range(data$obs, data$pred)
identity_line <- data.frame(x = x_range, y = x_range)

obspred_plot <- plotly::plot_ly(data, x = ~obs, y = ~pred, type = 'scatter', mode = 'markers') %>%
plotly::add_lines(data = identity_line, x = ~x, y = ~y, line = list(color = 'blue')) %>%

plotly::layout(title = list(text = title, x = 0.5),
xaxis = list(title = "Observed", showline = TRUE, zeroline = FALSE),
yaxis = list(title = "Predicted", showline = TRUE, zeroline = FALSE),
margin = list(t = 100),
showlegend = FALSE)

obspred_plot
```

```{r results="asis", echo = FALSE, eval = ("pred" %in% gsub("_(.*)", "", names(common$meta)))}
  cat("## Make Predictions")
```

```{r results="asis", echo = FALSE, eval = ("pred_pred" %in% names(common$meta))}
  cat("### Make predictions from model")
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("pred_pred" %in% names(common$meta))}
    map <- leaflet() %>%
      addProviderTiles("Esri.WorldTopoMap") 
  for (variable in c("Field", "Prediction (rate)", "Prediction (cases)", "IID")){
    if (!is.null(common$pred[[tolower(variable)]])){
      raster_map(map, common, common$pred[[tolower(variable)]], variable)
    }
  }
  if (!is.null(common$meta$pred_pred$uncertain)){
    raster_map(map, common, common$pred$uncertainty$predictions_ci$`lower CI`, "Lower credible interval")
    raster_map(map, common, common$pred$uncertainty$predictions_ci$`upper CI`, "Upper credible interval")
  }
```

```{r results="asis", echo = FALSE, eval = ("pred_transfer" %in% names(common$meta))}
  cat("### Make predictions over a new area")
```

```{r, echo=FALSE, fig.height=5, fig.align="center", eval = ("pred_transfer" %in% names(common$meta))}
    map <- leaflet() %>%
      addProviderTiles("Esri.WorldTopoMap") 
  ex <- as.vector(terra::ext(common$transfer$prediction))
  map |> fitBounds(lng1 = ex[[1]], lng2 = ex[[2]], lat1 = ex[[3]], lat2 = ex[[4]])
  raster_map(map, common, common$transfer$prediction, "Transferred prediction (rate)")
  raster_map(map, common, common$transfer$cases, "Transferred prediction (cases)")
  for (layer in names(common$transfer$covariates)){
    raster_map(map, common, common$transfer$covariates[[layer]], paste0(layer, " (transferred)"))
  }
```

