---
title: "How To Use disagapp"
output: html_document
---

### **Overview of** ***disagapp***
This information is designed to orient the user to the *disagapp* interface.

#### **Components and Modules**
*disagapp* is composed of **Components** – discrete steps in the workflow which need to be run consecutively. Navigate through the components by clicking on the names in the top navigation panel. 
  
Within each component, there are various major options that can be run. These are the ***modules***. Selecting a module opens the control panel to make decisions and run the module’s functionalities. Depending on the use case, an analysis may require using only one module in each component or multiple modules.
  
#### **Log Window and Visualization Panel**
Analyses performed will be detailed in the log window. This is also where error messages appear.

After running the functionalities of a *module*, outputs appear in the Visualization panel, which includes an interactive map, table and the Results tab where plots are displayed. The Visualization panel also includes guidance texts and the Save tab (see below).

#### **Guidance Texts**
Many scientific analyses require the researcher to make decisions and the guidance text provides information about the user with information about what the modules do and how to use them.

As the user proceeds through the workflow, the relevant guidance texts can be found to the right of the Results tab in the Visualization panel.

If more support is needed, the Support tab in the orange navigation bar at the top provides links to the shinyscholar homepage and email.

#### **Saving and Reproducing Results**
Users can stop an analysis and restart it later, by saving the workflow progress as an RDS file, found in the Save tab. This file can be loaded into *disagapp* later using the Intro component’s Load Prior Session tab, to restart the analysis where the user left off. 

Additionally, *disagapp* allows the user to download their results. After each step of analysis (i.e., after running each module), the results for that particular model may be downloaded from the Save tab in the Visualization panel. 

A great quality of *disagapp* is reproducibility. To download the session code or metadata (documenting all of the analyses run to that point in the Wallace session), use the **Reproduce** component. This includes the option of an R Markdown file that can be opened and rerun in R. 

Closing the browser window will terminate the analysis, but R will remain running. To close disagapp and stop functions running in R, use the power button in the top right corner in the navigation bar.
  

