---
title: "intro_tab"
output: html_document
---

#### WORKFLOW

*disagapp* (v0.0.1) includes seven components, or steps of a possible workflow. Each component includes one or more modules, which are possible analyses for that step. Modules are classified using a colour coding depending system dependent on whether they <span class="module_mandatory">must be used</span>, <span class="module_choice">at least one of several choices must be used</span>, <span class="module_optional">or they are optional</span>.

**Components:**  

**1.** *Response*  
- <span class="module_choice">Combine spreadsheet and shapefile</span>
- <span class="module_choice">Upload spreadsheet</span>
- <span class="module_choice">Upload shapefile</span>
- <span class="module_optional">Edit data</span>
- <span class="module_optional">Simplify polygons</span>

**2.** *Covariates*  
- <span class="module_choice">Accessibility</span>
- <span class="module_choice">Climate</span>
- <span class="module_choice">Distance to water</span>
- <span class="module_choice">Land use</span>
- <span class="module_choice">Nighttime lights</span>
- <span class="module_choice">Upload covariates</span>

**3.** *Aggregation*  
- <span class="module_choice">Population density</span>
- <span class="module_choice">Upload aggregation</span>
- <span class="module_choice">Uniform</span>

**4.** *Prepare*  
- <span class="module_mandatory">Generate mesh</span>
- <span class="module_mandatory">Summarise and resample covariates</span>
- <span class="module_optional">Covariate correlations</span>
- <span class="module_optional">Reduce covariate resolution</span>
- <span class="module_mandatory">Finalise data preparation</span>

**5.** *Fit*
- <span class="module_mandatory">Fit model</span>

**6.** *Predict*
- <span class="module_mandatory">Make predictions</span>

**7.** *Reproduce*  
- <span class="module_optional">Download session code</span>
- <span class="module_optional">Reproduce environment</span>
- <span class="module_optional">Download covariates</span>
- <span class="module_optional">Download package references</span>
