test_that("rep_covs downloads covariates", {
  skip_on_ci()
  skip_on_cran()
  app <- shinytest2::AppDriver$new(app_dir = system.file("shiny", package = "disagapp"), name = "e2e_cov_upload")
  app$set_inputs(tabs = "resp")
  app$set_inputs(respSel = "resp_shape")
  app$upload_file("resp_shape-shape" = shpdf$datapath)
  app$set_inputs("resp_shape-resp_var" = "inc")
  app$click("resp_shape-run")
  app$upload_file("cov_upload-cov" = covdf$datapath)
  app$click("cov_upload-run")
  app$set_inputs(tabs = "rep")
  app$set_inputs(repSel = "rep_covs")
  zip <- tempfile(fileext = ".zip")
  app$wait_for_value(input = "rep_covs-ready")
  app$get_download("rep_covs-download", filename = zip)
  td <- tempfile()
  dir.create(td)
  zip::unzip(zip, exdir = td)
  files <- list.files(td)
  expect_length(files, 4)
  app$stop()
})
