name: Daily Deployed App Tests

on:
  schedule:
    # Runs at 8:00 UTC every day
    - cron: '0 8 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  test-deployed-app:
    runs-on: ubuntu-latest

    steps:

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3'

    - name: Install required packages
      run: |
        R -e "install.packages(c('httr', 'chromote', 'shinytest2', 'testthat', 'jsonlite', 'processx'), repos = 'https://cloud.r-project.org')"
        R -e "if(!requireNamespace('remotes')) install.packages('remotes')"
        R -e "remotes::install_deps(dependencies = TRUE)"

    - name: Run tests against deployed app
      run: |
        Rscript -e '
        library(testthat)
        library(shinytest2)

        test_that("Deployed app is reachable", {
          response <- httr::GET("https://disagapp.le.ac.uk/")
          expect_equal(httr::status_code(response), 200)
        })

        test_that("Deployed app is responsive", {
          app <- AppDriver$new(
            "https://disagapp.le.ac.uk/",
            name = "deployed_app_test",
            load_timeout = 20000
          )

          app$set_inputs(tabs = "resp")
          app$set_inputs(respSel = "resp_example")
          app$click("resp_example-run")
          common <- app$get_value(export = "common")
          expect_is(common$shape, "sf")
          app$stop()
        })'

    - name: Save test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          shinytest2/_snaps/
          test-output.xml
